apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: devops-k8s-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-k8s-cicd
  template:
    metadata:
      labels:
        app: devops-k8s-cicd
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valuesFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: POSTGRES_USER
              valuesFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valuesFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
